### ISSUE TITLE
Validations missing on backend

### ISSUE THREAD

**Issue by Dhiren-NYU** [gcivil-nyu-org/Wednesday-Fall2023-Team-2#105]
Although validations are present on frontend sometimes people might integrate your api's in their application directly or just use api's directly to sabotage your application.
I was able to update occupancy to a negative percentage by directly calling api from postman.
![image](https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-2/assets/144502280/1611af4a-b4c5-4258-a41f-7f2e787f6ed6)
![image](https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-2/assets/144502280/ea9e543c-660f-4540-9b09-743b4c2f2f9f)

**Comment by NigelLu** [comment]
Thank you for testing Parkrowd and providing us this valuable feedback.

We have decided that in a later release, the occupancy would be level-based rather than percentage-based. In other words, users would be able to select from different levels of occupany like 10-20% full, 20-30% full. This shall alleviate the issue you mentioned.

Appreciate your effort to make Parkrowd better.
