### ISSUE TITLE
Validation on occupancy values

### ISSUE THREAD

**Issue by kravisankaran** [gcivil-nyu-org/Wednesday-Fall2023-Team-2#107]
I was allowed to enter an occupancy value like 30.899, however only when I tried to screenshot for evidence, did I see a small validation error pop up
Possibly should make this very explicit, and not allow the user to hit submit
<img width="454" alt="Screenshot 2023-11-16 at 7 47 21 PM" src="https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-2/assets/13433292/089b7989-ac79-444d-8f91-b89b5f007a72">
<img width="1792" alt="image" src="https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-2/assets/13433292/968f3964-77da-4b52-b64d-a0147a79eab7">

**Comment by NigelLu** [comment]
Thank you for testing Parkrowd and providing us this valuable feedback.

We have decided that in a later release, the occupancy would be level-based rather than percentage-based. In other words, users would be able to select from different levels of occupany like 10-20% full, 20-30% full. This shall alleviate the issue you mentioned.

Appreciate your effort to make Parkrowd better.
