### ISSUE TITLE
Verify Business upload

### ISSUE THREAD

**Issue by kravisankaran** [gcivil-nyu-org/Wednesday-Fall2023-Team-2#108]
I was able to submit a file that wasnt a supported type, although hitting the submit button did not give me any errors. Possibly  highlighting it more explicitly could be useful.
Would the address input be verified? It accepted a test address not part of the map
<img width="1792" alt="image" src="https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-2/assets/13433292/1676c356-0f35-47ce-ad9f-5330b4d84081">

**Comment by NigelLu** [comment]
Thank you for spotting this issue. It means a lot to Parkrowd.

We do need to look into this to add more robust validations on our input fields (frontend + backend validations). 

For the address validation you mentioned, we did not do this because this would require another Google Map API query call, adding even more to our tight Google API budget. But your feedback is absolutely valid and we appreciate your effort in make Parkrowd better.
