### ISSUE TITLE
Users can edit each other's profile

### ISSUE THREAD

**Issue by himanshu1196** [gcivil-nyu-org/Wednesday-Fall2023-Team-2#113]
What I did : Navigated to my user's Edit-Profile view. Changed the URL to try to edit a different user's profile (http://parkrowd-prod.us-west-2.elasticbeanstalk.com/users/profile-edit/test4/ to http://parkrowd-prod.us-west-2.elasticbeanstalk.com/users/profile-edit/test2/)

What went wrong : The app allowed me to edit and save the changes for user2! 

![Capture](https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-2/assets/14277620/bb6cfe80-a208-41a5-b783-581ba1290729)

**Comment by himanshu1196** [comment]
We missed this check too! But ensuring that request's user id is the same as the url in the corresponding view should fix it.

**Comment by NigelLu** [comment]
Thank you for spotting this issue. It means a lot to Parkrowd.
We will update our app to use cookie to extract which user is submitting POST requests to alleviate this issue (not just for verification, but all other POST). 

Yes, like you mentioned, ensuring the request user's id is the same as the URL could alleviate this. 
My proposed approach is to directly use `LoginRequiredMixin` alongside with `request.user` to retrieve any user related info. This essentially forces our app to recognize user only using the server-side Cookie database instead of trusting any input from POST body or URL pattern as anything from the client side could be vulnerable and not trust-worthy. Hope our method could also be of help to you.
